---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccounts.yaml
  - configmaps.yaml
  - services.yaml
  - deployments.yaml
  - pdbs.yaml
  - networkpolicies.yaml
