---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-ratelimit
  namespace: ai-gateway
  labels:
    app.kubernetes.io/name: envoy-ratelimit
    app.kubernetes.io/component: rate-limit-service
    app.kubernetes.io/part-of: ai-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: ai-gateway
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: demo-counter-store
    app.kubernetes.io/part-of: ai-gateway
automountServiceAccountToken: false
