---
apiVersion: v1
kind: Service
metadata:
  name: envoy-ratelimit
  namespace: ai-gateway
  labels:
    app.kubernetes.io/name: envoy-ratelimit
    app.kubernetes.io/component: rate-limit-service
    app.kubernetes.io/part-of: ai-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: envoy-ratelimit
    app.kubernetes.io/component: rate-limit-service
  ports:
    - name: grpc
      port: 8081
      targetPort: grpc
      protocol: TCP
    - name: http-debug
      port: 8080
      targetPort: http-debug
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ai-gateway
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: demo-counter-store
    app.kubernetes.io/part-of: ai-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: demo-counter-store
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
