---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ratelimit
  namespace: ai-gateway
spec:
  replicas: 3
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: envoy-ratelimit
              app.kubernetes.io/component: rate-limit-service
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: envoy-ratelimit
              app.kubernetes.io/component: rate-limit-service
      containers:
        - name: envoy-ratelimit
          env:
            - name: USE_STATSD
              value: "false"
            - name: LOG_LEVEL
              value: info
            - name: RUNTIME_ROOT
              value: /data
            - name: RUNTIME_SUBDIRECTORY
              value: ratelimit
            - name: RUNTIME_WATCH_ROOT
              value: "false"
            - name: REDIS_SOCKET_TYPE
              value: tcp
            - name: REDIS_URL
              value: external-ha-redis.ai-gateway.svc.cluster.local:6379
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-ratelimit
  namespace: ai-gateway
spec:
  minAvailable: 2
